//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "m_character")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "custom(\"MEDIUMINT(9)\")")]
    pub id: String,
    pub character_code: String,
    pub role_id: i32,
    pub role_code: String,
    pub active: Option<i32>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
