//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::m_account::Entity as MAccount;
pub use super::m_character::Entity as MCharacter;
pub use super::m_role::Entity as MRole;
pub use super::m_user::Entity as MUser;
pub use super::posts::Entity as Posts;
